# Generated by Django 4.0.4 on 2022-04-23 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm_samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('commentary', models.TextField(default='', verbose_name='Комментарий')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IncomeAccount', to='django_orm_samples.account', verbose_name='Счет поступления')),
                ('account_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OutcomeAccount', to='django_orm_samples.account', verbose_name='Счет расхода')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('commentary', models.TextField(default='', verbose_name='Комментарий')),
                ('sum_in', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыли',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('commentary', models.TextField(default='', verbose_name='Комментарий')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма в наличии')),
                ('diff_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма разница')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.account', verbose_name='Счет инвентаризации')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('commentary', models.TextField(default='', verbose_name='Комментарий')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.account', verbose_name='Счет')),
                ('currency_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IncomeCurrency', to='django_orm_samples.currency', verbose_name='Валюта покупки')),
                ('currency_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OutcomeCurrency', to='django_orm_samples.currency', verbose_name='Валюта продажи')),
            ],
            options={
                'verbose_name': 'Обмен валюты',
                'verbose_name_plural': 'Обмены валют',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('commentary', models.TextField(default='', verbose_name='Комментарий')),
                ('sum_out', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Затрата',
                'verbose_name_plural': 'Затраты',
            },
        ),
    ]
