# Generated by Django 4.0.4 on 2022-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm_samples', '0002_transfer_profit_inventory_currencyexchange_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='commentary',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='currencyexchange',
            old_name='commentary',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='commentary',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='profit',
            old_name='commentary',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='commentary',
            new_name='comment',
        ),
    ]
