# Generated by Django 3.2.13 on 2022-05-08 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm_samples', '0005_auto_20220501_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('short_name', models.CharField(default='', max_length=3)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='diff_sum',
            new_name='sum_diff',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='account_out',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='sum_out',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='account',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='currency_out',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='date',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='id',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='currencyexchange',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='account_in',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='sum_in',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='account_out',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sum',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='sum_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма разница'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='currency_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OutcomeCurrency', to='django_orm_samples.currency', verbose_name='Валюта покупки'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.currency', verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_records', to='django_orm_samples.budget', verbose_name='Статья')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_records', to='django_orm_samples.document', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_records', to='django_orm_samples.account', verbose_name='Счет')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_records', to='django_orm_samples.document', verbose_name='Документ')),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.budget', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orm_samples.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orm_samples.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.budget', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orm_samples.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='django_orm_samples.budget', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orm_samples.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_orm_samples.document'),
            preserve_default=False,
        ),
    ]
