# Generated by Django 3.2.13 on 2022-10-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm_samples', '0006_auto_20220508_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='slug',
            field=models.SlugField(default='default', max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
